<footer>
    <article class="footlinks">
        <div class="NarcusImg">
            <a href="mailto:104550871@student.swin.edu.au"><img src="images/Marcus.png" alt="Marcus"></a>
            <p>
                <strong>
                    <em>
                        Marcus
                    </em>
                </strong>
                <br>
                Index HTML & CSS
                <br>
                Jobs CSS
                <br>
                Nav Bar & Footer
                <br>
                Apply CSS
            </p>
        </div>

        <div class="JoshImg">
            <a href="mailto:104550240@student.swin.edu.au"><img src="images/Josh.png" alt="Josh"></a>
            <p>
                <strong>
                    <em>
                        Josh
                    </em>
                </strong>
                <br>
                About CSS & HTML
                <br>
                Enhancements CSS & HTML
            </p>
        </div>

        <div class="KyleImg">
            <a href="mailto:103155164@student.swin.edu.au"><img src="images/Kyle.png" alt="Kyle"></a>
            <p>
                <strong>
                    <em>
                        Kyle
                    </em>
                </strong>
                <br>
                Jobs HTML & CSS
                <br>
            </p>
        </div>

        <div class="VikImg">
            <a href="mailto:103815029@student.edu.au"><img src="images/Vik.png" alt="Vik"></a>
            <p>
                <strong>
                    <em>
                        Vik
                    </em>
                </strong>
                <br>
                Apply Page HTML & CSS
                <br>
            </p>
        </div>

        <div class="MikeImg">
            <img src="images/Mike.jpg" alt="Mike">
            <p>
                <strong>
                    <em>
                        Mike
                    </em>
                </strong>
            </p>
        </div>

    </article>
</footer>
