<a href="index.php"><img class="logo" src="images/TB&C.png" alt="logo"></a>
<nav>
    <ul class="Links">
        <li class="index"><a href="index.php">Index</a></li>
        <li class="jobs"><a href="jobs.php">Jobs</a></li>
        <li class="apply"><a href="apply.php">Apply</a></li>
        <li class="about"><a href="about.php">About</a></li>
        <li class="enhancements"><a href="enhancements.php">Enhancements</a></li>
        <li class="enhancements"><a href="phpenhancements.php">PHP Enhancements</a></li>
        <li class="email"><a href="mailto:104550871@student.swin.edu.au">Contact Us</a></li>
        <li class="login"><a href="login.php">Login</a></li>
    </ul>
</nav>
